import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import Navbar from "../components/layout/Navbar";
import { CircleProvider } from "../src/providers/CircleProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${interTight.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CircleProvider>
          <Navbar />
          {children}
        </CircleProvider>
      </body>
    </html>
  );
}
