import {
  ArrowDownLeft,
  ArrowUpRight,
  Banknote,
  PiggyBank,
  type LucideIcon,
} from "lucide-react";

import type { ActivityItem, AnalyticsStat, Group, GroupDetail } from "@/types";

export const mockGroups: Group[] = [
  {
    id: "group-coffee-circle",
    name: "Coffee Circle",
    currentRound: 2,
    totalRounds: 4,
    members: 8,
    maxMembers: 10,
    poolValue: 1600,
    nextPayoutDate: "2026-09-12",
    status: "active",
    contributionAmount: 100,
    interval: "weekly",
  },
  {
    id: "group-tech-savers",
    name: "Tech Savers",
    currentRound: 1,
    totalRounds: 3,
    members: 6,
    maxMembers: 8,
    poolValue: 1200,
    nextPayoutDate: "2026-09-08",
    status: "forming",
    contributionAmount: 150,
    interval: "monthly",
  },
  {
    id: "group-family-fund",
    name: "Family Fund",
    currentRound: 4,
    totalRounds: 4,
    members: 10,
    maxMembers: 10,
    poolValue: 2500,
    nextPayoutDate: "2026-09-05",
    status: "completed",
    contributionAmount: 200,
    interval: "monthly",
  },
];

export const mockPublicGroups: Group[] = [
  {
    id: "group-sunrise-savers",
    name: "Sunrise Savers",
    currentRound: 1,
    totalRounds: 5,
    members: 4,
    maxMembers: 8,
    poolValue: 900,
    nextPayoutDate: "2026-09-18",
    status: "forming",
    contributionAmount: 75,
    interval: "weekly",
    isPrivate: false,
  },
  {
    id: "group-tech-circle",
    name: "Tech Circle",
    currentRound: 2,
    totalRounds: 6,
    members: 6,
    maxMembers: 10,
    poolValue: 1400,
    nextPayoutDate: "2026-09-20",
    status: "active",
    contributionAmount: 125,
    interval: "weekly",
    isPrivate: false,
  },
  {
    id: "group-family-first-fund",
    name: "Family First Fund",
    currentRound: 3,
    totalRounds: 4,
    members: 7,
    maxMembers: 9,
    poolValue: 1800,
    nextPayoutDate: "2026-09-24",
    status: "active",
    contributionAmount: 150,
    interval: "monthly",
    isPrivate: false,
  },
];

export const mockActivity: ActivityItem[] = [
  {
    id: "activity-1",
    type: "received",
    description: "Payout received from round 2",
    amount: 600,
    date: "2 days ago",
    groupName: "Coffee Circle",
  },
  {
    id: "activity-2",
    type: "paid",
    description: "Contribution paid for this week",
    amount: 100,
    date: "4 days ago",
    groupName: "Tech Savers",
  },
  {
    id: "activity-3",
    type: "joined",
    description: "Joined the group",
    amount: null,
    date: "1 week ago",
    groupName: "Family Fund",
  },
  {
    id: "activity-4",
    type: "member_joined",
    description: "A new member joined the circle",
    amount: null,
    date: "1 week ago",
    groupName: "Coffee Circle",
  },
];

export const mockStats: AnalyticsStat[] = [
  {
    label: "Total Saved",
    value: "$2,400",
    icon: PiggyBank,
    description: "Across all active circles",
  },
  {
    label: "Total Received",
    value: "$1,200",
    icon: ArrowDownLeft,
    description: "Settled payouts this cycle",
  },
  {
    label: "Active Equbs",
    value: "3",
    icon: Banknote,
    description: "Groups currently contributing",
  },
  {
    label: "Next Contribution",
    value: "$100",
    icon: ArrowUpRight,
    description: "in 2 days",
  },
];

export const mockGroupDetail: GroupDetail = {
  id: "group-coffee-circle",
  name: "Coffee Circle",
  dagnaName: "Selam Bekele",
  dagnaAvatar: "SB",
  currentRound: 2,
  totalRounds: 4,
  contributionAmount: 100,
  interval: "weekly",
  maxMembers: 10,
  poolValue: 2400,
  members: [
    {
      id: "member-1",
      name: "Selam Bekele",
      wallet: "0xA1b2...C3d4",
      avatar: "SB",
      hasPaid: true,
      hasReceived: false,
      isCurrentWinner: true,
      joinedAt: "May 13, 2026",
    },
    {
      id: "member-2",
      name: "Hanna Tadesse",
      wallet: "0xD4e5...F6g7",
      avatar: "HT",
      hasPaid: true,
      hasReceived: false,
      joinedAt: "May 13, 2026",
    },
    {
      id: "member-3",
      name: "Mikiyas Alem",
      wallet: "0xH8i9...J0k1",
      avatar: "MA",
      hasPaid: true,
      hasReceived: true,
      joinedAt: "May 15, 2026",
    },
    {
      id: "member-4",
      name: "Tigist Negash",
      wallet: "0xL2m3...N4o5",
      avatar: "TN",
      hasPaid: false,
      hasReceived: false,
      joinedAt: "May 17, 2026",
    },
    {
      id: "member-5",
      name: "Abel Fekadu",
      wallet: "0xP6q7...R8s9",
      avatar: "AF",
      hasPaid: true,
      hasReceived: false,
      joinedAt: "May 19, 2026",
    },
    {
      id: "member-6",
      name: "Dawit Solomon",
      wallet: "0xT1u2...V3w4",
      avatar: "DS",
      hasPaid: true,
      hasReceived: false,
      joinedAt: "May 21, 2026",
    },
    {
      id: "member-7",
      name: "Netsanet Biru",
      wallet: "0xX5y6...Z7a8",
      avatar: "NB",
      hasPaid: false,
      hasReceived: false,
      joinedAt: "May 23, 2026",
    },
    {
      id: "member-8",
      name: "Yohannes Bekele",
      wallet: "0xB9c1...D2e3",
      avatar: "YB",
      hasPaid: true,
      hasReceived: false,
      joinedAt: "May 25, 2026",
    },
  ],
  winners: [
    {
      round: 1,
      name: "Hanna Tadesse",
      wallet: "0xD4e5...F6g7",
      amount: 800,
      paidAt: "2026-07-12T00:00:00.000Z",
    },
    {
      round: 2,
      name: "Selam Bekele",
      wallet: "0xA1b2...C3d4",
      amount: 900,
      paidAt: "2026-08-16T00:00:00.000Z",
    },
  ],
};
